import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { Suspense } from "react";
import QueryProvider from './providers/QueryProvider';
import { FavoritesProvider } from '@/contexts/FavoritesContext';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          {/* <Suspense fallback={<div>Loading...</div>}> */}
            <FavoritesProvider>
              {children}
            </FavoritesProvider>
          {/* </Suspense> */}
        </QueryProvider>
      </body>
    </html>
  );
}
